const employeeMedicalHeader = {
  dateOfExamination: 'Date of Examination',
  employeeId: 'Employee ID',
  lastName: 'Last Name',
  firstName: 'First Name',
  middleName: 'Middle Name',
  nameExtension: 'Name Extension',
  gender: 'Gender',
  dateOfBirth: 'Date of Birth',
  age: 'Age',
  academicYear: 'Academic Year',
  role: 'Role',
  weightKg: 'Weight (Kg)',
  heightCm: 'Height (Cm)',
  temperature: 'Temperature',
  bloodPressure: 'Blood Pressure',
  heartRate: 'Heart Rate',
  pulseRate: 'Pulse Rate',
  respiratoryRate: 'Respiratory Rate',
  visionScreening: 'Vision Screening',
  auditoryScreening: 'Auditory Screening',
  skinScreening: 'Skin Screening',
  scalpScreening: 'Scalp Screening',
  eyesScreening: 'Eyes Screening',
  earScreening: 'Ear Screening',
  noseScreening: 'Nose Screening',
  mouthScreening: 'Mouth Screening',
  throatScreening: 'Throat Screening',
  neckScreening: 'Neck Screening',
  lungScreening: 'Lung Screening',
  heartScreening: 'Heart Screening',
  abdomen: 'Abdomen',
  deformities: 'Deformities',
  remarks: 'Remarks',
  status: 'Status',
};

export default employeeMedicalHeader;
