const studentMedicalHeader = {
  dateOfExamination: 'Date of Examination',
  lrn: 'LRN',
  lastName: 'Last Name',
  firstName: 'First Name',
  middleName: 'Middle Name',
  nameExtension: 'Name Extension',
  gender: 'Gender',
  dateOfBirth: 'Date of Birth',
  age: 'Age',
  schoolYear: 'School Year',
  grade: 'Grade',
  section: 'Section',
  is4p: '4P Status',
  weightKg: 'Weight (kg)',
  heightCm: 'Height (cm)',
  bmi: 'BMI',
  bmiClassification: 'BMI Classification',
  heightForAge: 'Height for Age',
  beneficiaryOfSBFP: 'SBFP Status',
  temperature: 'Temperature',
  bloodPressure: 'Blood Pressure',
  heartRate: 'Heart Rate',
  pulseRate: 'Pulse Rate',
  respiratoryRate: 'Respiratory Rate',
  visionScreening: 'Vision Screening',
  auditoryScreening: 'Auditory Screening',
  skinScreening: 'Skin Screening',
  scalpScreening: 'Scalp Screening',
  eyesScreening: 'Eyes Screening',
  earScreening: 'Ear Screening',
  noseScreening: 'Nose Screening',
  mouthScreening: 'Mouth Screening',
  throatScreening: 'Throat Screening',
  neckScreening: 'Neck Screening',
  lungScreening: 'Lung Screening',
  heartScreening: 'Heart Screening',
  abdomen: 'Abdomen',
  deformities: 'Deformities',
  ironSupplementation: 'Iron Supplementation',
  deworming: 'Deworming',
  menarche: 'Menarche',
  remarks: 'Remarks',
  status: 'Status',
};

export default studentMedicalHeader;
