import Joi from 'joi';

const studentMedicalValidationSchema = Joi.object({
  dateOfExamination: Joi.date().required(),
  lrn: Joi.string().required(),
  lastName: Joi.string().required(),
  firstName: Joi.string().required(),
  middleName: Joi.string().allow('', null),
  nameExtension: Joi.string().allow('', null),
  gender: Joi.string().required(),
  dateOfBirth: Joi.date().required(),
  age: Joi.number().integer().required(),
  schoolYear: Joi.string().required(),
  grade: Joi.string().required(),
  section: Joi.string().required(),
  is4p: Joi.boolean().required(),
  weightKg: Joi.number().required(),
  heightCm: Joi.number().required(),
  bmiClassification: Joi.string().required(),
  heightForAge: Joi.string().required(),
  beneficiaryOfSBFP: Joi.boolean().required(),
  temperature: Joi.number().required(),
  bloodPressure: Joi.string().required(),
  heartRate: Joi.number().required(),
  pulseRate: Joi.number().required(),
  respiratoryRate: Joi.number().required(),
  visionScreening: Joi.string().required(),
  auditoryScreening: Joi.string().required(),
  skinScreening: Joi.string().required(),
  scalpScreening: Joi.string().required(),
  eyesScreening: Joi.string().required(),
  earScreening: Joi.string().required(),
  noseScreening: Joi.string().required(),
  mouthScreening: Joi.string().required(),
  throatScreening: Joi.string().required(),
  neckScreening: Joi.string().required(),
  lungScreening: Joi.string().required(),
  heartScreening: Joi.string().required(),
  abdomen: Joi.string().required(),
  deformities: Joi.string().required(),
  ironSupplementation: Joi.boolean().required(),
  deworming: Joi.boolean().required(),
  menarche: Joi.string().allow('', null),
  remarks: Joi.string().allow('', null),
  status: Joi.string()
    .valid('Active', 'Archived', 'Inactive')
    .default('Active'),
});

export const validateStudentMedical = (data) => {
  return studentMedicalValidationSchema.validate(data, { abortEarly: false });
};

const headerMappings = {
  dateOfExamination: 'Date of Examination',
  lrn: 'LRN',
  lastName: 'Last Name',
  firstName: 'First Name',
  middleName: 'Middle Name',
  nameExtension: 'Name Extension',
  gender: 'Gender',
  dateOfBirth: 'Date of Birth',
  age: 'Age',
  schoolYear: 'School Year',
  grade: 'Grade',
  section: 'Section',
  is4p: 'Is 4P',
  weightKg: 'Weight (Kg)',
  heightCm: 'Height (Cm)',
  bmiClassification: 'BMI Classification',
  heightForAge: 'Height for Age',
  beneficiaryOfSBFP: 'Beneficiary of SBFP',
  temperature: 'Temperature',
  bloodPressure: 'Blood Pressure',
  heartRate: 'Heart Rate',
  pulseRate: 'Pulse Rate',
  respiratoryRate: 'Respiratory Rate',
  visionScreening: 'Vision Screening',
  auditoryScreening: 'Auditory Screening',
  skinScreening: 'Skin Screening',
  scalpScreening: 'Scalp Screening',
  eyesScreening: 'Eyes Screening',
  earScreening: 'Ear Screening',
  noseScreening: 'Nose Screening',
  mouthScreening: 'Mouth Screening',
  throatScreening: 'Throat Screening',
  neckScreening: 'Neck Screening',
  lungScreening: 'Lung Screening',
  heartScreening: 'Heart Screening',
  abdomen: 'Abdomen',
  deformities: 'Deformities',
  ironSupplementation: 'Iron Supplementation',
  deworming: 'Deworming',
  menarche: 'Menarche',
  remarks: 'Remarks',
  status: 'Status',
};

export const mapHeaderToSchemaKey = (header) => {
  return headerMappings[header] || header;
};
